### ISSUE TITLE
infografia_hilos_AngelAntonioLopez

### ISSUE THREAD

**Issue by Angel-antonio03** [SistemasTecTlaxiaco/infografia-de-hilos-Angel-antonio03#2]
https://drive.google.com/file/d/1yHj9TaFcktpK55rVAFg_5y18kcYKytZu/view?usp=drive_link

**Comment by HECTOR-KDM02** [comment]
19 puntos

Mejorar la ortografía y el diseño tiene que ser mas creativo y no tan monótono y repetitivo además el tamaño de letra es demasiado grande y puede llegar a molestar el bajar 2 paginas para leer información

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
